name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for 30 seconds to avoid deployment conflicts
        run: sleep 130  # Adding delay to avoid conflicts with container restart

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3  # Updated to v3 for better compatibility
        with:
          app-name: SGCF24  # Replace with your Azure App name
          slot-name: "production" 
          
      - name: Check deployment status
        run: |
          echo "Deployment finished. Checking for errors..."
          # Optional step to check the deployment log if needed
          curl -s https://sgcf24.scm.azurewebsites.net/api/deployments/temp-7818501b/log
